server {
    listen 80 default_server;
    server_name _;

    root /var/www/inventory-app;
    index index.html;

    auth_basic           "inventory-app";
    auth_basic_user_file /etc/nginx/.htpasswd;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
