server {
    listen 80 default_server;
    server_name _;

    root /var/www/inventory-app;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
